#!/usr/bin/env bash
#
# The keys wizard: walks Shahmeer through the steps only he can click, so
# the contact form (ADR-0004) can send. The Resend key, the Turnstile widget
# and the three variables in Vercel and in .env.local, each step ending with
# a check that it took. From the repo root: bash docs/agents/keys-wizard.sh
# It removes nothing, ever: a key or a widget made in error is deleted by
# hand in the dashboard that made it.
#
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# The values are written to .env.local, which git ignores, so a re-run
# offers what the last run saved and skips what already checks out.
ENV_FILE=".env.local"

# The Resend endpoints, Cloudflare's siteverify and the live site.
RESEND_API="https://api.resend.com"
RESEND_KEYS_URL="https://resend.com/api-keys"
RESEND_DOMAINS_URL="https://resend.com/domains"
TURNSTILE_URL="https://dash.cloudflare.com/?to=/:account/turnstile"
SITEVERIFY="https://challenges.cloudflare.com/turnstile/v0/siteverify"
VERCEL_URL="https://vercel.com/dashboard"
SITE="https://www.shahmeerasim.me"
DEV_SITE="http://localhost:3000"
ROUTE_PATH="/api/contact"

# ── Preflight: the tools, the repo, and the addresses the content names ──
fail() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }

for tool in curl node npm; do
  command -v "$tool" >/dev/null 2>&1 || fail "$tool is needed and was not found."
done
[[ -f content/site.ts && -f package.json ]] ||
  fail "Run this from the repo root: bash docs/agents/keys-wizard.sh"

# The route sends from contactMail.from to contact.email; both are read off
# the content module so the wizard and the site can never name two addresses.
GMAIL=$(grep -oE '^\s*email: "[^"]+"' content/site.ts | head -n1 | sed -E 's/.*"([^"]+)"/\1/' || true)
FROM=$(grep -oE 'from: "[^"]+"' content/site.ts | head -n1 | sed -E 's/.*"([^"]+)"/\1/' || true)
[[ -n "$GMAIL" && -n "$FROM" ]] ||
  fail "content/site.ts no longer names contact.email and contactMail.from where this wizard reads them."
DOMAIN=$(printf '%s' "$FROM" | sed -E 's/.*@([^>[:space:]]+)>?.*/\1/')

# vercel: the CLI if installed, else fetched by npx for this run.
vercel() {
  if type -P vercel >/dev/null 2>&1; then command vercel "$@"; else npx --yes vercel "$@"; fi
}

# ── Checks: each stage ends in one of these, and skips when it passes ────

# _resend_send KEY FROM SUBJECT TEXT: one send, printing "<status> <body>".
_resend_send() {
  local key="$1" from="$2" subject="$3" text="$4" body
  body=$(printf '{"from":"%s","to":["%s"],"subject":"%s","text":"%s"}' "$from" "$GMAIL" "$subject" "$text")
  curl -s -X POST "$RESEND_API/emails" \
    -H "Authorization: Bearer $key" -H "Content-Type: application/json" \
    -d "$body" -w ' %{http_code}' 2>/dev/null | sed -E 's/^(.*) ([0-9]{3})$/\2 \1/' || true
}

# resend_key_check KEY: passes only for a key that can send and do nothing
# else, pinned to the site's domain. Two probes, neither of which should
# get as far as sending:
#  1. Listing domains must be refused as `restricted_api_key`, the answer
#     Resend documents for a sending-only key. A key that can list them is
#     full access, and full access reaches the agency's mail.
#  2. Sending from a made-up domain must be refused for a reason other
#     than the domain being unverified. "Not verified" is the documented
#     answer of a key free to use any verified domain, the agency's
#     included; a key pinned to one domain is refused for the pin. Resend
#     does not document the pinned key's wording, so the check reads for
#     the free key's, and prints what it saw when it refuses.
resend_key_check() {
  local key="$1" answer
  answer=$(curl -s "$RESEND_API/domains" -H "Authorization: Bearer $key" 2>/dev/null || true)
  if grep -qi 'invalid' <<<"$answer"; then
    warn "Resend does not know that key. It answered: $answer"
    return 1
  fi
  if ! grep -q 'restricted_api_key' <<<"$answer"; then
    warn "The key is not sending-only: it can read the account. Resend answered: ${answer:-nothing}"
    return 1
  fi
  answer=$(_resend_send "$key" "wizard@not-$DOMAIN" "Keys wizard: scope probe" "Never sent; this probes the key's domain.")
  case "$answer" in
    2*)
      warn "The key sent from a domain that is not $DOMAIN, so it is not pinned to it. Delete it at $RESEND_KEYS_URL."
      return 1 ;;
  esac
  if grep -qi 'not verified' <<<"$answer"; then
    warn "The key may send from any verified domain, not $DOMAIN alone. Resend answered: $answer"
    note "If the key's row at $RESEND_KEYS_URL does say Sending access and $DOMAIN, Resend's wording has changed: tell the agent."
    return 1
  fi
  return 0
}

# turnstile_secret_check SECRET: siteverify with a token that is not one
# answers "invalid-input-response" for a real secret and
# "invalid-input-secret" for anything else. Cloudflare's always-passing
# testing secret answers success, and is refused by name: in Vercel it
# would wave every bot through.
turnstile_secret_check() {
  local answer
  answer=$(curl -s -X POST "$SITEVERIFY" --data-urlencode "secret=$1" --data-urlencode "response=keys-wizard" 2>/dev/null || true)
  if grep -q 'result_with_testing_key' <<<"$answer"; then
    warn "That is Cloudflare's testing secret, not the widget's. It passes every Token."
    return 1
  fi
  if grep -q 'invalid-input-secret' <<<"$answer" || ! grep -q 'invalid-input-response' <<<"$answer"; then
    warn "Cloudflare does not know that secret. It answered: ${answer:-nothing}"
    return 1
  fi
}

# page_has_site_key URL KEY: the site key is inlined into the page at build
# time, so the page carrying it is the widget being handed it. The page is
# read whole before it is searched: under pipefail, a grep that stops at
# the first match would fail the curl behind it.
page_has_site_key() {
  local page
  page=$(curl -s "$1" 2>/dev/null || true)
  grep -qF "$2" <<<"$page"
}

# vercel_has NAME ENVIRONMENT: the variable reads back from Vercel, by
# name; a sensitive value is never shown again, by anyone.
vercel_has() {
  local listed
  listed=$(vercel env ls "$2" 2>/dev/null || true)
  grep -qE "(^|[[:space:]])$1([[:space:]]|$)" <<<"$listed"
}

# route_status: what the deployed route answers a JSON post with every field
# good and a Token that is not one. 403 is the Token refused at siteverify,
# which only a route holding both secrets gets to; 503 is a secret missing.
route_status() {
  curl -s -o /dev/null -w '%{http_code}' -X POST "$SITE$ROUTE_PATH" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"Keys wizard\",\"email\":\"$GMAIL\",\"message\":\"A probe from the keys wizard; nothing is sent.\",\"cf-turnstile-response\":\"keys-wizard\"}" \
    2>/dev/null || true
}

banner "The contact form's keys: Resend, Turnstile and Vercel"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Resend: a key that can only send, only from $DOMAIN"
RESEND_BEFORE=$(_existing RESEND_API_KEY || true)
if [[ -n "$RESEND_BEFORE" ]] && resend_key_check "$RESEND_BEFORE"; then
  RESEND_API_KEY="$RESEND_BEFORE"
  say "${GREEN}✓${RESET} The key in $ENV_FILE is sending-only and pinned to $DOMAIN. Nothing to do."
else
  say "The portfolio gets its own key, never the agency's: sending access, one domain."
  open_url "$RESEND_KEYS_URL"
  step "Click Create API Key."
  step "Name: Portfolio ($DOMAIN)."
  step "Permission: Sending access. Not Full access."
  step "Domain: $DOMAIN. This is what keeps a leak away from the agency's mail."
  step "Click Add, then copy the key. Resend shows it once; it starts re_."
  until ask_secret RESEND_API_KEY "Paste the key:" && resend_key_check "$RESEND_API_KEY"; do
    warn "That key will not do. Make one as the steps say and paste it; Ctrl-C to stop."
    note "A key made in error is deleted by hand at $RESEND_KEYS_URL; this wizard removes nothing."
  done
  say "${GREEN}✓${RESET} The key is sending-only and pinned to $DOMAIN."
  write_env RESEND_API_KEY "$RESEND_API_KEY"
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Resend: the domain, already verified, confirmed by one send"
say "$DOMAIN was verified in Resend before this wizard (Tokyo region), so it"
say "is not set up again: one message from $FROM to $GMAIL is the check."
answer=$(_resend_send "$RESEND_API_KEY" "$FROM" "Keys wizard: the domain sends" "If this arrived, $DOMAIN is verified in Resend and the key can send from it.")
case "$answer" in
  2*)
    say "${GREEN}✓${RESET} Resend accepted it, which it does only from a verified domain."
    open_url "https://mail.google.com/"
    step "Find \"Keys wizard: the domain sends\" in $GMAIL. Spam too, the first time."
    pause "Press Enter once it is there."
    ;;
  *)
    if grep -qi 'not verified' <<<"$answer"; then
      open_url "$RESEND_DOMAINS_URL"
      fail "$DOMAIN is not verified in Resend any more. Verify it there (the records are at Vercel's DNS), then run this wizard again. Resend answered: $answer"
    fi
    fail "Resend refused the send. It answered: $answer"
    ;;
esac

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: the Turnstile widget"
SITE_KEY_BEFORE=$(_existing NEXT_PUBLIC_TURNSTILE_SITE_KEY || true)
SECRET_BEFORE=$(_existing TURNSTILE_SECRET_KEY || true)
if [[ -n "$SITE_KEY_BEFORE" && -n "$SECRET_BEFORE" ]] && turnstile_secret_check "$SECRET_BEFORE"; then
  NEXT_PUBLIC_TURNSTILE_SITE_KEY="$SITE_KEY_BEFORE"
  TURNSTILE_SECRET_KEY="$SECRET_BEFORE"
  say "${GREEN}✓${RESET} Cloudflare knows the secret in $ENV_FILE, and the site key is beside it. Nothing to do."
else
  say "One widget, in managed mode, for the live site, the local dev server and"
  say "the Vercel preview, so the Form works in all three and nowhere else."
  open_url "$VERCEL_URL"
  step "Open the portfolio project → Settings → Domains, and find the hostname ending vercel.app."
  note "Turnstile covers a hostname's subdomains, not its siblings, and a per-branch preview URL is a sibling: name the hostname previews are opened at."
  ask VERCEL_HOST "The project's vercel.app hostname:"
  open_url "$TURNSTILE_URL"
  step "Click Add widget."
  step "Widget name: Portfolio."
  step "Hostnames: add $DOMAIN, localhost and ${VERCEL_HOST:-the vercel.app hostname}, one at a time."
  step "Widget mode: Managed."
  step "Pre-clearance: no."
  step "Click Create, then copy the Site Key and the Secret Key from the widget's page."
  until ask NEXT_PUBLIC_TURNSTILE_SITE_KEY "Paste the site key (public, starts 0x):" && [[ "$NEXT_PUBLIC_TURNSTILE_SITE_KEY" == 0x* ]]; do
    warn "A Turnstile site key starts 0x."
  done
  until ask_secret TURNSTILE_SECRET_KEY "Paste the secret key:" && turnstile_secret_check "$TURNSTILE_SECRET_KEY"; do
    warn "That is not a secret Cloudflare knows. Copy it from the widget's page; Ctrl-C to stop."
  done
  say "${GREEN}✓${RESET} Cloudflare knows the secret."
  write_env NEXT_PUBLIC_TURNSTILE_SITE_KEY "$NEXT_PUBLIC_TURNSTILE_SITE_KEY"
  write_env TURNSTILE_SECRET_KEY "$TURNSTILE_SECRET_KEY"
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The widget renders: the site key on the local page"
say "The page is handed the site key at build time; the dev server reads it"
say "from $ENV_FILE. Then your eyes: the Form must draw the widget above Send."
until page_has_site_key "$DEV_SITE/" "$NEXT_PUBLIC_TURNSTILE_SITE_KEY"; do
  warn "$DEV_SITE is not serving a page carrying the site key."
  step "In another terminal, at the repo root, run: npm run dev"
  note "If it was already running, stop it and start it again, so it reads $ENV_FILE."
  pause "Press Enter once it says Ready."
done
say "${GREEN}✓${RESET} The local page carries the site key."
open_url "$DEV_SITE/#contact"
step "On Contact, look at the Form: a Turnstile box sits above Send and settles to a tick."
confirm "Is the widget drawn, and does it settle?" ||
  fail "The site key is on the page but the widget did not draw. Check the widget's hostnames include localhost; if the site key pasted is not the widget's, delete its line from $ENV_FILE and run this again to paste it afresh."
say "${GREEN}✓${RESET} The widget renders."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Vercel: the three variables, Production and Preview"
say "Set through the Vercel CLI, marked sensitive, so no value is ever shown again,"
say "and read back by name after."
if ! vercel whoami >/dev/null 2>&1; then
  step "Log in to Vercel in the browser the CLI opens."
  vercel login
fi
if [[ ! -f .vercel/project.json ]]; then
  step "Link this directory to the Vercel project (the portfolio, not the agency)."
  vercel link
fi
CHANGED=""
[[ "$RESEND_API_KEY" != "$RESEND_BEFORE" ]] && CHANGED="1"
[[ "$TURNSTILE_SECRET_KEY" != "$SECRET_BEFORE" ]] && CHANGED="1"
[[ "$NEXT_PUBLIC_TURNSTILE_SITE_KEY" != "$SITE_KEY_BEFORE" ]] && CHANGED="1"
for name in RESEND_API_KEY TURNSTILE_SECRET_KEY NEXT_PUBLIC_TURNSTILE_SITE_KEY; do
  for environment in production preview; do
    if vercel_has "$name" "$environment"; then
      if [[ -z "$CHANGED" ]]; then
        say "${GREEN}✓${RESET} $name is set for $environment."
        continue
      fi
      # A value is replaced only when a key changed this run, and only
      # once asked: the old one is gone for good.
      confirm "$name is already set for $environment. Replace it with this run's value?" ||
        fail "Left as it was. Run this again once you know which value $environment should hold."
    fi
    printf '%s' "${!name}" | vercel env add "$name" "$environment" --sensitive --force >/dev/null ||
      fail "vercel env add $name $environment failed. Run it by hand and re-run this wizard."
    vercel_has "$name" "$environment" ||
      fail "$name was added for $environment but does not read back from Vercel."
    say "${GREEN}✓${RESET} $name set for $environment, and reads back."
  done
done
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Vercel: a fresh build carrying the site key"
say "The site key is inlined at build time, so the live page carries it only"
say "after a deploy that came after stage 5. The two secrets are read at runtime."
until page_has_site_key "$SITE/" "$NEXT_PUBLIC_TURNSTILE_SITE_KEY"; do
  warn "The live page does not carry the site key yet."
  open_url "$VERCEL_URL"
  step "Open the portfolio project → Deployments → the latest Production deployment → ⋯ → Redeploy."
  step "Leave \"Use existing Build Cache\" unticked, and wait for it to say Ready."
  note "Merging a pull request into main deploys too, if one is waiting."
  pause "Press Enter once it is Ready."
done
say "${GREEN}✓${RESET} The live page carries the site key."
status=$(route_status)
case "$status" in
  403) say "${GREEN}✓${RESET} The live route holds both secrets: a Token that is not one is refused at siteverify." ;;
  503) fail "The live route answers 503: it is running without a secret. Check stage 5's names in Vercel, then redeploy." ;;
  *)   fail "The live route answered $status to a probe, not the 403 expected. Check the deploy's logs in Vercel." ;;
esac
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The last check: one Message through the deployed route"
say "Everything so far was a probe. This is the real thing, sent by the Form"
say "as a Recruiter would send it, and read in your inbox."
open_url "$SITE/#contact"
step "In the Form: Name \"Keys wizard\", Email $GMAIL, and a Message of a sentence or two."
step "Press Send, and wait for the line saying it was sent."
open_url "https://mail.google.com/"
step "Find \"A message from the portfolio\" in $GMAIL, from $FROM, with Reply-To your own address."
confirm "Did it arrive?" ||
  fail "The Form said sent but nothing arrived, or the Form refused. Check Resend's Emails page for the send and its status."
say "${GREEN}✓${RESET} The Form reaches the inbox."
note "This wizard created nothing it could remove and removed nothing: the key, the widget and the variables stay."
pause

finish
