import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/*
         * The reveal in app/globals.css hides a block until JavaScript marks
         * it arrived. With JavaScript off nothing ever would, so this hands
         * every block straight back and the page reads in full.
         */}
        <noscript
          dangerouslySetInnerHTML={{
            __html: "<style>.reveal{opacity:1;transform:none}</style>",
          }}
        />
        {children}
      </body>
    </html>
  );
}
